##DO NOT USE commas in this file

org.nrg.Role=DicomEdit
org.nrg.Role.DicomEdit.key=DicomEdit
org.nrg.Role.DicomEdit.name=Dicom Edit 
org.nrg.Role.DicomEdit.warning=WARNING: Only approved user can access Dicom Edit pages of the web interface.
org.nrg.Role.DicomEdit.description=This allows users to edit DICOM files.