
org.nrg.Feature=DicomEdit
org.nrg.Feature.DicomEdit.key=DicomEdit
org.nrg.Feature.DicomEdit.name=Dicom Edit
org.nrg.Feature.DicomEdit.OnByDefault=false
org.nrg.Feature.DicomEdit.description= Allows user to edit DICOM files
